// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: latency.proto

package ptzpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PTZService_SendCommand_FullMethodName = "/ptz.PTZService/SendCommand"
)

// PTZServiceClient is the client API for PTZService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PTZServiceClient interface {
	SendCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PTZAck, PTZCommand], error)
}

type pTZServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPTZServiceClient(cc grpc.ClientConnInterface) PTZServiceClient {
	return &pTZServiceClient{cc}
}

func (c *pTZServiceClient) SendCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PTZAck, PTZCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PTZService_ServiceDesc.Streams[0], PTZService_SendCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PTZAck, PTZCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PTZService_SendCommandClient = grpc.BidiStreamingClient[PTZAck, PTZCommand]

// PTZServiceServer is the server API for PTZService service.
// All implementations must embed UnimplementedPTZServiceServer
// for forward compatibility.
type PTZServiceServer interface {
	SendCommand(grpc.BidiStreamingServer[PTZAck, PTZCommand]) error
	mustEmbedUnimplementedPTZServiceServer()
}

// UnimplementedPTZServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPTZServiceServer struct{}

func (UnimplementedPTZServiceServer) SendCommand(grpc.BidiStreamingServer[PTZAck, PTZCommand]) error {
	return status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedPTZServiceServer) mustEmbedUnimplementedPTZServiceServer() {}
func (UnimplementedPTZServiceServer) testEmbeddedByValue()                    {}

// UnsafePTZServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PTZServiceServer will
// result in compilation errors.
type UnsafePTZServiceServer interface {
	mustEmbedUnimplementedPTZServiceServer()
}

func RegisterPTZServiceServer(s grpc.ServiceRegistrar, srv PTZServiceServer) {
	// If the following call panics, it indicates UnimplementedPTZServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PTZService_ServiceDesc, srv)
}

func _PTZService_SendCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PTZServiceServer).SendCommand(&grpc.GenericServerStream[PTZAck, PTZCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PTZService_SendCommandServer = grpc.BidiStreamingServer[PTZAck, PTZCommand]

// PTZService_ServiceDesc is the grpc.ServiceDesc for PTZService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PTZService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ptz.PTZService",
	HandlerType: (*PTZServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendCommand",
			Handler:       _PTZService_SendCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "latency.proto",
}
