// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: latency.proto

package ptzpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PTZCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"` // pan, tilt, zoom, stop
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`    // speed or position value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTZCommand) Reset() {
	*x = PTZCommand{}
	mi := &file_latency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTZCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTZCommand) ProtoMessage() {}

func (x *PTZCommand) ProtoReflect() protoreflect.Message {
	mi := &file_latency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTZCommand.ProtoReflect.Descriptor instead.
func (*PTZCommand) Descriptor() ([]byte, []int) {
	return file_latency_proto_rawDescGZIP(), []int{0}
}

func (x *PTZCommand) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PTZCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *PTZCommand) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PTZAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PTZAck) Reset() {
	*x = PTZAck{}
	mi := &file_latency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PTZAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTZAck) ProtoMessage() {}

func (x *PTZAck) ProtoReflect() protoreflect.Message {
	mi := &file_latency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTZAck.ProtoReflect.Descriptor instead.
func (*PTZAck) Descriptor() ([]byte, []int) {
	return file_latency_proto_rawDescGZIP(), []int{1}
}

var File_latency_proto protoreflect.FileDescriptor

const file_latency_proto_rawDesc = "" +
	"\n" +
	"\rlatency.proto\x12\x03ptz\"L\n" +
	"\n" +
	"PTZCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\"\b\n" +
	"\x06PTZAck2=\n" +
	"\n" +
	"PTZService\x12/\n" +
	"\vSendCommand\x12\v.ptz.PTZAck\x1a\x0f.ptz.PTZCommand(\x010\x01B\"Z latency_poc/internal/ptzpb;ptzpbb\x06proto3"

var (
	file_latency_proto_rawDescOnce sync.Once
	file_latency_proto_rawDescData []byte
)

func file_latency_proto_rawDescGZIP() []byte {
	file_latency_proto_rawDescOnce.Do(func() {
		file_latency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_latency_proto_rawDesc), len(file_latency_proto_rawDesc)))
	})
	return file_latency_proto_rawDescData
}

var file_latency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_latency_proto_goTypes = []any{
	(*PTZCommand)(nil), // 0: ptz.PTZCommand
	(*PTZAck)(nil),     // 1: ptz.PTZAck
}
var file_latency_proto_depIdxs = []int32{
	1, // 0: ptz.PTZService.SendCommand:input_type -> ptz.PTZAck
	0, // 1: ptz.PTZService.SendCommand:output_type -> ptz.PTZCommand
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_latency_proto_init() }
func file_latency_proto_init() {
	if File_latency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_latency_proto_rawDesc), len(file_latency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_latency_proto_goTypes,
		DependencyIndexes: file_latency_proto_depIdxs,
		MessageInfos:      file_latency_proto_msgTypes,
	}.Build()
	File_latency_proto = out.File
	file_latency_proto_goTypes = nil
	file_latency_proto_depIdxs = nil
}
