// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: latency.proto

package latencypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LatencyService_Measure_FullMethodName = "/latency.LatencyService/Measure"
)

// LatencyServiceClient is the client API for LatencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LatencyServiceClient interface {
	Measure(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LatencyRequest, LatencyResponse], error)
}

type latencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLatencyServiceClient(cc grpc.ClientConnInterface) LatencyServiceClient {
	return &latencyServiceClient{cc}
}

func (c *latencyServiceClient) Measure(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LatencyRequest, LatencyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LatencyService_ServiceDesc.Streams[0], LatencyService_Measure_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LatencyRequest, LatencyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LatencyService_MeasureClient = grpc.BidiStreamingClient[LatencyRequest, LatencyResponse]

// LatencyServiceServer is the server API for LatencyService service.
// All implementations must embed UnimplementedLatencyServiceServer
// for forward compatibility.
type LatencyServiceServer interface {
	Measure(grpc.BidiStreamingServer[LatencyRequest, LatencyResponse]) error
	mustEmbedUnimplementedLatencyServiceServer()
}

// UnimplementedLatencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLatencyServiceServer struct{}

func (UnimplementedLatencyServiceServer) Measure(grpc.BidiStreamingServer[LatencyRequest, LatencyResponse]) error {
	return status.Error(codes.Unimplemented, "method Measure not implemented")
}
func (UnimplementedLatencyServiceServer) mustEmbedUnimplementedLatencyServiceServer() {}
func (UnimplementedLatencyServiceServer) testEmbeddedByValue()                        {}

// UnsafeLatencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LatencyServiceServer will
// result in compilation errors.
type UnsafeLatencyServiceServer interface {
	mustEmbedUnimplementedLatencyServiceServer()
}

func RegisterLatencyServiceServer(s grpc.ServiceRegistrar, srv LatencyServiceServer) {
	// If the following call panics, it indicates UnimplementedLatencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LatencyService_ServiceDesc, srv)
}

func _LatencyService_Measure_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LatencyServiceServer).Measure(&grpc.GenericServerStream[LatencyRequest, LatencyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LatencyService_MeasureServer = grpc.BidiStreamingServer[LatencyRequest, LatencyResponse]

// LatencyService_ServiceDesc is the grpc.ServiceDesc for LatencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LatencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "latency.LatencyService",
	HandlerType: (*LatencyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Measure",
			Handler:       _LatencyService_Measure_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "latency.proto",
}
