// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: latency.proto

package latencypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LatencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SentAtNs      int64                  `protobuf:"varint,2,opt,name=sent_at_ns,json=sentAtNs,proto3" json:"sent_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyRequest) Reset() {
	*x = LatencyRequest{}
	mi := &file_latency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyRequest) ProtoMessage() {}

func (x *LatencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_latency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyRequest.ProtoReflect.Descriptor instead.
func (*LatencyRequest) Descriptor() ([]byte, []int) {
	return file_latency_proto_rawDescGZIP(), []int{0}
}

func (x *LatencyRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LatencyRequest) GetSentAtNs() int64 {
	if x != nil {
		return x.SentAtNs
	}
	return 0
}

type LatencyResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SentAtNs           int64                  `protobuf:"varint,2,opt,name=sent_at_ns,json=sentAtNs,proto3" json:"sent_at_ns,omitempty"`
	ClientReceivedAtNs int64                  `protobuf:"varint,3,opt,name=client_received_at_ns,json=clientReceivedAtNs,proto3" json:"client_received_at_ns,omitempty"`
	ServerReceivedAtNs int64                  `protobuf:"varint,4,opt,name=server_received_at_ns,json=serverReceivedAtNs,proto3" json:"server_received_at_ns,omitempty"`
	RttNs              int64                  `protobuf:"varint,5,opt,name=rtt_ns,json=rttNs,proto3" json:"rtt_ns,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LatencyResponse) Reset() {
	*x = LatencyResponse{}
	mi := &file_latency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyResponse) ProtoMessage() {}

func (x *LatencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_latency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyResponse.ProtoReflect.Descriptor instead.
func (*LatencyResponse) Descriptor() ([]byte, []int) {
	return file_latency_proto_rawDescGZIP(), []int{1}
}

func (x *LatencyResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LatencyResponse) GetSentAtNs() int64 {
	if x != nil {
		return x.SentAtNs
	}
	return 0
}

func (x *LatencyResponse) GetClientReceivedAtNs() int64 {
	if x != nil {
		return x.ClientReceivedAtNs
	}
	return 0
}

func (x *LatencyResponse) GetServerReceivedAtNs() int64 {
	if x != nil {
		return x.ServerReceivedAtNs
	}
	return 0
}

func (x *LatencyResponse) GetRttNs() int64 {
	if x != nil {
		return x.RttNs
	}
	return 0
}

var File_latency_proto protoreflect.FileDescriptor

const file_latency_proto_rawDesc = "" +
	"\n" +
	"\rlatency.proto\x12\alatency\">\n" +
	"\x0eLatencyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\n" +
	"sent_at_ns\x18\x02 \x01(\x03R\bsentAtNs\"\xbc\x01\n" +
	"\x0fLatencyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\n" +
	"sent_at_ns\x18\x02 \x01(\x03R\bsentAtNs\x121\n" +
	"\x15client_received_at_ns\x18\x03 \x01(\x03R\x12clientReceivedAtNs\x121\n" +
	"\x15server_received_at_ns\x18\x04 \x01(\x03R\x12serverReceivedAtNs\x12\x15\n" +
	"\x06rtt_ns\x18\x05 \x01(\x03R\x05rttNs2R\n" +
	"\x0eLatencyService\x12@\n" +
	"\aMeasure\x12\x17.latency.LatencyRequest\x1a\x18.latency.LatencyResponse(\x010\x01B*Z(latency_poc/internal/latencypb;latencypbb\x06proto3"

var (
	file_latency_proto_rawDescOnce sync.Once
	file_latency_proto_rawDescData []byte
)

func file_latency_proto_rawDescGZIP() []byte {
	file_latency_proto_rawDescOnce.Do(func() {
		file_latency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_latency_proto_rawDesc), len(file_latency_proto_rawDesc)))
	})
	return file_latency_proto_rawDescData
}

var file_latency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_latency_proto_goTypes = []any{
	(*LatencyRequest)(nil),  // 0: latency.LatencyRequest
	(*LatencyResponse)(nil), // 1: latency.LatencyResponse
}
var file_latency_proto_depIdxs = []int32{
	0, // 0: latency.LatencyService.Measure:input_type -> latency.LatencyRequest
	1, // 1: latency.LatencyService.Measure:output_type -> latency.LatencyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_latency_proto_init() }
func file_latency_proto_init() {
	if File_latency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_latency_proto_rawDesc), len(file_latency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_latency_proto_goTypes,
		DependencyIndexes: file_latency_proto_depIdxs,
		MessageInfos:      file_latency_proto_msgTypes,
	}.Build()
	File_latency_proto = out.File
	file_latency_proto_goTypes = nil
	file_latency_proto_depIdxs = nil
}
